Add problems from years 2015-2019 & Fix typo at readme
648trindade/SBAC-PAD-marathon-problems pull request #2
Opened 2020-10-25 00:23 UTC by Alves-Bruno

2020-10-25 01:12 UTC, 648trindade commented on 2015/serial/A/Makefile
> +	icpc -std=c++11 -Wall -O3 huffman.cc -o huffman
Please change all Makefile `icc` and `icpc` references to `gcc` and `g++` references, respectively.
Also make sure that all problems can be built and run with the inputs provided.

2020-10-25 01:12 UTC, 648trindade commented on 2015/misc/inputs/C.in
> +1 1 0
Please remove all these duplicated input files. All input files should be placed at `misc/inputs` directory

2020-10-25 01:12 UTC, 648trindade commented on 2019/serial/D/Makefile
> +CFLAGS = -g -Wall -Wno-deprecated -O3 -march=native -std=c11
Make sure that no serial problem is being built with `-g` or `-O0` flags. Replace them with `-O2` flags

2020-10-25 01:16 UTC, 648trindade requested changes
Please add a `X.sh` (where `X` is the problem letter) shell script at each problem, in order that we can make it run by simply calling
```
bash X.sh
```
without specifying the input file or any other runtime environment variables

You can use the shell scripts from 2006 and 2008 problems as a base

2021-01-28 19:27 UTC, closed without merging

2021-01-28 19:30 UTC, Alves-Bruno commented
This PR was too big. I'll do new ones with smaller contributions. Thanks @648trindade  for the advice.